### ISSUE TITLE
ability to translate author description with WPML and Polylang

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/simple-author-box#85]

**Comment by razvanaldea89** [comment]
Both can translate the author bio, Polylang adds another textarea to the author bio with the required language and WPML cam be translated with Strings translation by selecting an option from the string translation plugin settings

**Comment by giucu91** [comment]
@razvanaldea89 can you describe this a bit more and in greater detail how to do this for each plugin so we can add it to our FAQ on wp.org ?

**Comment by razvanaldea89** [comment]
Polylang:
Using this plugin the "Biographical Info" is added for each language, so each language gets a textarea that corresponds to the  "Biographical Info" for the respective language.
WPML:
In order to translate the  "Biographical Info" using this plugin the user has to have to wpml-string-translation plugin installed and the following configurations made :
- in the String Translation settings at the bottom there is a "More options" setting. Click "Edit" and select "Author" from there then click "Apply". After this, in the filters above, at "Select strings within domain" select "Authors". This will reveal the strings that can be translated from the author role.

**Comment by giucu91** [comment]
Added in readme.txt
